name: 'Build app with vite'

on:
  workflow_call:
    secrets:
      GOOGLE_CLIENT_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > .env
      - run: pnpm install
      - run: pnpm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist